global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'accubooks-app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'

  - job_name: 'accubooks-postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'accubooks-redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'accubooks-nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
