apiVersion: v1
kind: Service
metadata:
  name: accubooks-backend
  namespace: accubooks-prod
  labels:
    app: accubooks-backend
spec:
  type: ClusterIP
  selector:
    app: accubooks-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
