apiVersion: v1
kind: Service
metadata:
  name: accubooks-frontend
  namespace: accubooks-prod
  labels:
    app: accubooks-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: accubooks-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
