apiVersion: v1
kind: ServiceAccount
metadata:
  name: accubooks-backend-sa
  namespace: accubooks-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::971551576768:role/accubooks-production-backend-sa-role
